name: Deploy engorg

on:
  push:
    branches: [main]
    paths: ['engorg/**', '.github/workflows/deploy-engorg.yml']
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        type: choice
        options:
          - plan
          - apply

permissions:
  contents: read

jobs:
  deploy:
    uses: 56kcloud/acme-iacplatform-githubworkflows/.github/workflows/terraform-deploy.yml@8af9606df9b5fd7e7d6074907d89201264c3b6bc # v0.1.3
    permissions:
      contents: read
      id-token: write       # OIDC for AWS credentials
      pull-requests: write  # Terraform plan as PR comment
    with:
      deploy-env: engorg
      action: ${{ inputs.action }}
    secrets:
      GITHUBMCH_REPOS_READ_APP_PRIVATE_KEY: ${{ secrets.GITHUBMCH_REPOS_READ_APP_PRIVATE_KEY }}
      TFC_REGISTRY_READ_TOKEN: ${{ secrets.TFC_REGISTRY_READ_TOKEN }}
